### ISSUE TITLE
Any change of getting stereochemistry detection?

### ISSUE THREAD

**Issue by stanstrup** [rajarshi/cdkr#28]
Seems it is included with the cdk: http://cdk.github.io/cdk/1.5/docs/api/org/openscience/cdk/stereo/Stereocenters.html
what I would like to be able to do is detect which atoms are potential chiral centers.

**Comment by rajarshi** [comment]
Better late than never. Atom centered stereo support implemented in 553e745914

**Comment by allaway** [comment]
@rajarshi thanks for implementing this. I've noticed that none of the fingerprinting methods accessible in rcdk consider stereochemistry (or, I'm doing something wrong). Is this correct?

**Comment by rajarshi** [comment]
You're correct - none of the fingerprints were designed to consider stereo. Come to think of it I'm not sure any of the published fingerprint take into account stereo

**Comment by allaway** [comment]
Thanks for the confirmation! Surprising there is nothing out there.

**Comment by rajarshi** [comment]
Though I do see this as an issue with other toolkits, e.g., https://github.com/rdkit/rdkit/issues/695

It might be worth pinging the CDK list to see if there is interest in adding optional support for stereochem to the ECFP implementation

**Comment by allaway** [comment]
Thanks for the suggestion. I did some digging on the CDK mailing list and found a reference to this commit: https://github.com/cdk/cdk/commit/ef55233d4b5a8c0a9a3724bf5862604c7ff9e937

Looks like it should already be implemented! 💯
