### ISSUE TITLE
eval.desc fails with parLapply

### ISSUE THREAD

**Issue by stanstrup** [rajarshi/cdkr#30]
Following the example for "eval.desc"
```
smiles <- c('CCC', 'c1ccccc1', 'CC(=O)C')
mols <- sapply(smiles, parse.smiles)

dnames <- get.desc.names('topological')
descs <- eval.desc(mols, dnames, verbose=TRUE)
```

you can do

```
lapply(dnames,function(x){ require(rcdk); eval.desc(mols, x, verbose=FALSE)})
```

which works but this

```
cl <- makeCluster(detectCores()-1)
clusterExport(cl, "mols")
rcdk_desc <- parLapply(cl,dnames,function(x){ require(rcdk); eval.desc(mols, x, verbose=FALSE)})
stopCluster(cl)
```

fails with

```
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: java.lang.NullPointerException
```

Applying over "mols" instead of "dnames" does not produce an error but all are NA.

I realize this is probably some java/parallel interaction but do you have any idea of a workaround?

**Comment by rajarshi** [comment]
Unfortunately, the CDK is not threadsafe (at least the version that is used in rcdk), so running it in parallel leads to all sorts of errors and is not advised.

**Comment by egonw** [comment]
It actually gives NAs no matter what... even for things where threadsafety should not matter (like molecular weight...)...
