### ISSUE TITLE
fp.sim.matrix fplist2 issue

### ISSUE THREAD

**Issue by allaway** [rajarshi/cdkr#52]
Hi there,

Thanks for a great R package. I'm encountering an issue with fp.sim.matrix() wherein fplist2 seems to be always interpreted as null even when I provide a second list of fingerprints. 

Eg: 

fp1 is a list of 8500 fingerprints
fp2 is a list of 2500 fingerprints

```fp.sim <- fp.sim.matrix(fplist =  fp1, fplist2 = fp2, method='tanimoto') ```

fp.sim ends up being a 8500x8500 matrix, rather than 8500x2500. 

I am running R 3.4.0, fingerprint version 3.3.8.

Cheers,
Robert

**Comment by rajarshi** [comment]
Fixed in the Github master (v3.5.5)

**Comment by allaway** [comment]
Ah perfect. Thanks so much!
