### ISSUE TITLE
support for CDK's MolecularFormulaGenerator

### ISSUE THREAD

**Issue by egonw** [rajarshi/cdkr#55]
With an R API something like:

    > elementRanges <- matrix(c("C", 1, 10, "H", 0, 22), ncol=3, byrow=T)
    > formulas <- rcdk.getFormulas(mass, tolerance, elementRanges)

The CDK API is described in https://github.com/cdk/cdk-paper-3/blob/master/formula_generator_benchmark/CDK/CDKFormulaGeneratorCLI.java

**Comment by rajarshi** [comment]
A first version is now implemented in `master` and uses the `RoundRobinFormulaGenerator` class. To guard against excessively large lists of formula being generated, the method returns an iterator. To retrieve formulae, you must iterate. By default the formulae are returned as strings. But if desired `IMolecularFormula` objects can be returned
 
The function takes element ranges as a list. The function is defined as

```
generate.formula2 <- function(mass, window = 0.01,
                              elements = list(
                                C=c(0,50),
                                H=c(0,50),
                                N=c(0,50),
                                O=c(0,50),
                                S=c(0,50)),
                              validation = FALSE,
                              charge = 0.0,
                              as.string=TRUE)
```

and example usage is

```
library(rcdk)
library(itertools)
it <- generate.formula2(200, as.string=TRUE)
## get all formula at one go
forms <- as.list(enumerate(it))
## manually iterate
it <- generate.formula2(200, as.string=TRUE)
hit <- ihasNext(it)
while (hasNext(hit)) 
  print(nextElem(hit))
```

Probably should come up with a better name. Also need to add docs.

**Comment by rajarshi** [comment]
As for speed-up, I'm seeing ~ 30x compare to the current method

```
library(rcdk)
library(itertools)
it <- generate.formula2(500, as.string=FALSE)
system.time(f2 <- as.list(enumerate(it))
system.time(f1 <- generate.formula(500))
```
