### ISSUE TITLE
CDKR fails to compile via command line

### ISSUE THREAD

**Issue by bachi55** [rajarshi/cdkr#71]
Hei, 

I cloned the latest version of the repository and tried to compile the library using the command line:
```bash
R CMD build rcdklibs
R CMD INSTALL rcdklibs_*gz
cd rcdkjar
ant clean jar
cd ../
R CMD build rcdk # <-- Produces error
R CMD INSTALL rcdk_*gz
```
The ```R CMD build rcdk``` command fails with the following error-message:
```bash
creating vignettes ... ERROR
Quitting from lines 110-115 (molform.Rmd) 
Error: processing vignette 'molform.Rmd' failed with diagnostics:
Elements must be 3-tuples or 4-tuples
```
I fixed the `molform.Rmd` file by changing the lines 110-111:
```R
mit <- generate.formula.iter(100, charge=0, window=0.1,
                             elements=list(C=c(0,50), H=c(0,50), N=c(0,50)))
```
to:
```R
mit <- generate.formula.iter(100, charge=0, window=0.1,
                             elements=list(c("C",0,50), c("H",0,50), c("N",0,50)))
```
to be compatible with the `generate.formula.iter` function definition in [`rcdk/R/formula.R`](https://github.com/rajarshi/cdkr/blob/1f9e213e98973b00316bc5d27c35aa936504c619/rcdk/R/formula.R). 

However, I receive another compilation error, that I could not fix now:
```bash
creating vignettes ... ERROR
Quitting from lines 110-115 (molform.Rmd) 
Error: processing vignette 'molform.Rmd' failed with diagnostics:
method getString with signature (Lorg/openscience/cdk/interfaces/IMolecularFormula;ZZ)Ljava/lang/String; not found
```
This seems to be related to the command in line 245-246 in file [`rcdk/R/formula.R`](https://github.com/rajarshi/cdkr/blob/1f9e213e98973b00316bc5d27c35aa936504c619/rcdk/R/formula.R):
```R
return(.jcall("org/openscience/cdk/tools/manipulator/MolecularFormulaManipulator",
      "S", "getString", formula, FALSE, TRUE))
```

Can you help with that? 

Best regards,

Eric

**Comment by rajarshi** [comment]
Thanks for the report. But after I apply your fix, `R CMD BUILD rcdk` proceeds with no error. I'm running R 3.5.0

Can you try the latest version?

**Comment by bachi55** [comment]
Hei,

sorry for coming back to this problem with such a delay. I tested your latest version (repository cloned today) and the building now works. I am on R version 3.5.0 as well now.

Can be closed. 

Best regards,

Eric

**Comment by rajarshi** [comment]
Thanks
