### ISSUE TITLE
Need to Update for Java 11

### ISSUE THREAD

**Issue by zachcp** [rajarshi/cdkr#75]
@rajarshi ,

I received an email from CRAN about fixing an `rcdk` version check before the release to Java 11. I didn't update a fix in time and noticed that as of this morning I have been booted from Maintainership as of `rcdk`  (see https://cran.r-project.org/web/packages/rcdk/rcdk.pdf)

I will look into a fix of the Java version test to patch an updated version, but I don't know if I will be able to submit the patch. Build error and and correction updated below.  A fix will need to 
either:

1. Fix the Java11 issue but avoid your recent updates which require a more recent CDK
2.  Update the rCDKlibs with a new release and then add the Java 11 Patch to master.

Any preferences on which route to take?

zach cp

```
* testing if installed package can be loaded
Warning in fun(libname, pkgname) : NAs introduced by coercion
Error: package or namespace load failed for ‘rcdk’:
  .onLoad failed in loadNamespace() for 'rcdk', details:
   call: if (isjavagood == FALSE) {
   error: missing value where TRUE/FALSE needed

jversion evaluates as 11-ea+22" .

The code in 'Writing R Extensions' does work portably,

Please correct ASAP and before Sep 25 (the currently expected release
date for Java 11).
```

**Comment by rajarshi** [comment]
It's probably a good idea to make a new release of `rcdklibs` and patch master.

**Comment by rajarshi** [comment]
Just submitted the latest `rcdklibs` (2.2.1)

**Comment by zachcp** [comment]
ok. i'll take a look at applying the batch and building/submitting.

zcp
