### ISSUE TITLE
Include hydrogens in plots

### ISSUE THREAD

**Issue by trljcl** [rajarshi/cdkr#9]
Hydrogens are not included in plots (using view.image.2d or view.molecule.2d) functions.  This is confusing when plotting structures containing, for example, hydroxyl groups.  I suspect this is caused by the following default assigment in these functions of:

molecule = AtomContainerManipulator.removeHydrogens(molecule)

This assignment should be updated to include the following options:

1) No hydrogens (default; current behaviour)
2) All atoms (i.e. including all hydrogens; less useful but probably easy to implement)
3) All hydrogens not attached to a carbon (most useful option)

**Comment by rajarshi** [comment]
Should be fixed in current version
